[package]
name = "ssmpl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#![recursion_limit = "256"]
[dependencies]
termcolor = "1.1.2"
